run:
  timeout: 5m
  go: '1.22'

linters:
  enable:
    - gofmt
    - goimports
    - govet
    - errcheck
    - staticcheck
    - unused
    - gosimple
    - ineffassign
    - typecheck
    - gosec
    - misspell
    - unconvert
    - gocritic
    - revive

linters-settings:
  gosec:
    excludes:
      - G204 # Subprocess launched with variable
  revive:
    rules:
      - name: exported
        disabled: true

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gosec